name: ci

on:
  push:
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v2

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Check typescript compilation
        run: npm run check:tsc

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run coverage:all
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          MAP_QUEST_API_KEY: ${{ secrets.MAP_QUEST_API_KEY }}
          HERE_APP_ID: ${{ secrets.HERE_APP_ID }}
          HERE_APP_CODE: ${{ secrets.HERE_APP_CODE }}

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.node-version, '14')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
